<script lang="ts">
    import { goto } from "$app/navigation";
    import { toast } from "svelte-sonner";
    import { Button } from "$lib/components/ui/button";
    import { Input } from "$lib/components/ui/input";
    import { Textarea } from "$lib/components/ui/textarea";
    import { Skeleton } from "$lib/components/ui/skeleton";
    import { ArrowLeft, RefreshCw, CheckCircle, Plus, QrCode, AlertTriangle } from "lucide-svelte";
    import QRCode from "qrcode";
    import PageContainer from "$lib/components/ui_components_sveltekit/layout/PageContainer.svelte";
    import PageHeader from "$lib/components/ui_components_sveltekit/layout/PageHeader.svelte";
    import PageContent from "$lib/components/ui_components_sveltekit/layout/PageContent.svelte";
    import FormCard from "$lib/components/ui_components_sveltekit/form/FormCard.svelte";
    import FormContainer from "$lib/components/ui_components_sveltekit/form/FormContainer.svelte";
    import FormRow from "$lib/components/ui_components_sveltekit/form/FormRow.svelte";
    import FormField from "$lib/components/ui_components_sveltekit/form/FormField.svelte";
    import FormActions from "$lib/components/ui_components_sveltekit/form/FormActions.svelte";
    import QRCodeDisplay from "$lib/components/ui_components_sveltekit/whatsapp/QRCodeDisplay.svelte";
    import { whatsAppStore } from "$lib/stores/whatsapp-store";
    import type { ConnectionStatus } from "$lib/stores/whatsapp-store";
    import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "$lib/components/ui/card";
    import type { PageData } from './$types';
    import { writable, derived } from 'svelte/store';
    import { onDestroy } from 'svelte';
    
    // Import the reusable form handler
    import { createFormHandler } from '$lib/components/ui_components_sveltekit/form/utils/formHandler';
    
    export let data: PageData;
    const title = "Create WhatsApp Account";

    // Define breadcrumbs for this page
    const pageCrumbs = [
        ["Admin", "/admin"],
        ["Settings", "/admin/settings"],
        ["WhatsApp Accounts", "/admin/settings/whatsapp/accounts"],
        "New Account",
    ];
    
    // Track the current step in the account creation process
    let currentStep = 1; // 1: Connect WhatsApp, 2: Account Details, 3: Success
    
    // Account data after creation
    let createdAccount: { id?: string; description: string } | null = null;
    
    // Use the client ID from the server (generated by Baileys)
    let initialClientId = data.clientId || null;
    
    // Create a store for our form-specific state
    const formState = writable<{
        clientId: string | null;
        connectionStatus: ConnectionStatus;
        qrCode: string | null;
        pushName: string | null;
        phoneNumber: string | null;
    }>({
        clientId: initialClientId,
        connectionStatus: 'disconnected',
        qrCode: null,
        pushName: null,
        phoneNumber: null
    });
    
    // Create a readable store for the client ID
    const formClientId = derived(formState, $state => $state.clientId);
    
    // Create a derived store for the form's WhatsApp state
    const formWhatsAppState = derived(formState, $state => ({
        connectionStatus: $state.connectionStatus,
        qrCode: $state.qrCode,
        pushName: $state.pushName,
        phoneNumber: $state.phoneNumber
    }));
    
    // Subscribe to the WhatsApp store to update our form state
    const unsubscribe = whatsAppStore.subscribe($store => {
        // Log for debugging
        console.log('WhatsApp store updated:', {
            storeClientId: $store.clientId,
            formClientId: $formState.clientId,
            storeQrCode: $store.qrCode ? 'present' : 'null',
            storeConnectionStatus: $store.connectionStatus
        });
        
        // Update our form state when the store's client ID matches our form's client ID
        formState.update($state => {
            // If the store has our client ID, update our state
            if ($store.clientId === $state.clientId) {
                return {
                    ...$state,
                    connectionStatus: $store.connectionStatus,
                    qrCode: $store.qrCode,
                    pushName: $store.pushName,
                    phoneNumber: $store.phoneNumber
                };
            }
            
            // Otherwise, keep our state as is
            return $state;
        });
    });
    
    // Clean up subscription when component is destroyed
    onDestroy(unsubscribe);
    
    // Log form-specific WhatsApp state changes for debugging
    $: console.log('Form WhatsApp state changed:', {
        connectionStatus: $formWhatsAppState.connectionStatus,
        clientId: $formClientId,
        qrCode: $formWhatsAppState.qrCode ? 'present' : 'null',
        currentStep
    });
    
    // Watch the form-specific WhatsApp state for connection status changes
    $: if ($formWhatsAppState.connectionStatus === 'connected' || $formWhatsAppState.connectionStatus === 'authenticated') {
        console.log('Connected status detected for form client:', $formClientId);
        
        if (currentStep === 1) {
            console.log('Advancing to step 2');
            
            // Pre-fill the form with the data from the connected client
            const pushName = $formWhatsAppState.pushName || 'Unknown';
            const phoneNumber = $formWhatsAppState.phoneNumber || '';
            
            console.log('WhatsApp client info:', {
                pushName,
                phoneNumber,
                clientId: $formClientId
            });
            
            // Update form values directly
            $form.description = `WhatsApp Account - ${pushName}`;
            $form.client_id = $formClientId;
            $form.name = pushName;
            $form.phoneNumber = phoneNumber;
            
            // Move to account details step
            currentStep = 2;
            toast.success('WhatsApp connected successfully!');
        }
    }
    
    // Create a form handler with standardized error handling
    const { form, errors, enhance, submitting, constraints, errorMessage } = createFormHandler(data.form, {
        validateOnInput: true,
        debugMode: true,
        onSuccess: (result) => {
            if (result.data?.account) {
                createdAccount = {
                    id: result.data.account.id,
                    description: result.data.account.description
                };
                
                // Move to success page
                currentStep = 3;
                toast.success("WhatsApp account created successfully");
            }
        }
    });

    // Function to request a new WhatsApp client (which will trigger a QR code event)
    async function requestNewQRCode() {
        console.log('Requesting new WhatsApp client');
        
        // Reset the WhatsApp store first to clear any errors
        whatsAppStore.reset();
        
        // Show loading toast
        const toastId = toast.loading('Creating new WhatsApp client...');
        
        try {
            // Call the server-side action to create a new client
            // This will trigger Baileys to create a new client and generate a QR code
            const response = await fetch('?/requestQRCode', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                }
            });
            
            const result = await response.json();
            
            if (result.success && result.clientId) {
                // Update our form state with the new client ID from Baileys
                formState.update(state => ({
                    ...state,
                    clientId: result.clientId,
                    connectionStatus: 'disconnected',
                    qrCode: null
                }));
                
                // Dismiss the loading toast and show success
                toast.dismiss(toastId);
                toast.success('New WhatsApp client created. Waiting for QR code...');
            } else {
                // Dismiss the loading toast and show error
                toast.dismiss(toastId);
                toast.error('Failed to create new WhatsApp client');
            }
        } catch (error) {
            console.error('Error creating new WhatsApp client:', error);
            // Dismiss the loading toast and show error
            toast.dismiss(toastId);
            toast.error('Error creating new WhatsApp client');
        }
    }
    
    // Handle error events
    function handleError(event: CustomEvent) {
        console.error('WhatsApp error:', event.detail);
        toast.error(event.detail.message || 'An error occurred');
    }
    
    // Function to check connection status and advance to next step
    function checkConnectionAndAdvance() {
        if ($formWhatsAppState.connectionStatus === 'connected' || $formWhatsAppState.connectionStatus === 'authenticated') {
            // Pre-fill the form with the data from the connected client
            const pushName = $formWhatsAppState.pushName || 'Unknown';
            const phoneNumber = $formWhatsAppState.phoneNumber || '';
            
            // Update form values directly
            $form.description = `WhatsApp Account - ${pushName}`;
            $form.client_id = $formClientId;
            $form.name = pushName;
            $form.phoneNumber = phoneNumber;
            
            // Move to account details step
            currentStep = 2;
            toast.success('WhatsApp connected successfully!');
        } else {
            toast.error('WhatsApp is not connected yet. Please scan the QR code first.');
        }
    }
    
    // Generate QR code from data
    async function generateQRCode(qrCodeData: string) {
        if (!qrCodeData) {
            console.log('No QR code data available');
            return null;
        }
        
        console.log('Generating QR code from data:', qrCodeData.substring(0, 20) + '...');
        
        try {
            // Use QRCode library to generate a data URL
            const url = await QRCode.toDataURL(qrCodeData, {
                errorCorrectionLevel: 'H', // High error correction for better scanning
                margin: 1,
                width: 256,
                color: {
                    dark: '#000000',
                    light: '#FFFFFF'
                }
            });
            
            console.log('QR code generated successfully');
            return url;
        } catch (err) {
            console.error('Error generating QR code:', err);
            throw err;
        }
    }
</script>

<PageContainer crumbs={pageCrumbs}>
    <PageHeader title={title} />

    <PageContent>
        
        {$formWhatsAppState.connectionStatus}

        {#if currentStep === 1}
            <!-- QR Code Display Step -->
            <FormCard title="Connect WhatsApp" description="Scan the QR code with your WhatsApp app to connect this account.">
                <!-- Simple QR code display -->
                <div class="flex flex-col items-center justify-center space-y-4 p-4">
                    <!-- Debug info for connection status -->
                    <div class="text-xs text-muted-foreground mb-2 p-2 bg-muted/30 rounded w-full">
                        <p>Connection status: <span class="font-medium">{$formWhatsAppState.connectionStatus}</span></p>
                        <p>Client ID: <span class="font-medium">{$formClientId || 'Not connected'}</span></p>
                    </div>
                    
                    {#if $formWhatsAppState.qrCode}
                        <!-- Show QR code when available -->
                        <div class="w-64 h-64 border border-border rounded-md overflow-hidden flex items-center justify-center bg-white">
                            {#await generateQRCode($formWhatsAppState.qrCode)}
                                <!-- Loading state while generating QR code -->
                                <Skeleton class="h-64 w-64" />
                            {:then qrCodeUrl}
                                <!-- QR code image -->
                                <img 
                                    src={qrCodeUrl} 
                                    alt="WhatsApp QR Code" 
                                    class="w-full h-full object-contain"
                                />
                            {:catch error}
                                <!-- Error state -->
                                <div class="text-center text-destructive">
                                    <AlertTriangle class="h-12 w-12 mx-auto mb-2" />
                                    <p class="text-sm">Failed to generate QR code</p>
                                </div>
                            {/await}
                        </div>
                        <p class="text-sm text-center text-muted-foreground">
                            Scan this QR code with your WhatsApp app to connect
                        </p>
                    {:else if $formWhatsAppState.connectionStatus === 'connecting'}
                        <!-- Loading state when connecting -->
                        <div class="w-64 h-64 flex items-center justify-center">
                            <Skeleton class="h-64 w-64" />
                        </div>
                        <Skeleton class="h-4 w-48" />
                    {:else}
                        <!-- No QR code available state -->
                        <div class="w-64 h-64 border-2 border-dashed border-muted-foreground rounded-md flex items-center justify-center">
                            <div class="text-center">
                                <QrCode class="h-12 w-12 mx-auto mb-2 text-muted-foreground" />
                                <p class="text-sm text-muted-foreground">QR code not available</p>
                            </div>
                        </div>
                        <p class="text-sm text-center text-muted-foreground">
                            Click the button below to request a QR code
                        </p>
                    {/if}
                </div>
                    
                <div class="mt-4 flex flex-col gap-2">
                    <!-- Request new QR code button -->
                    <Button 
                        variant="outline" 
                        size="sm"
                        on:click={requestNewQRCode}
                    >
                        <RefreshCw class="h-4 w-4 mr-2" />
                        Request New QR Code
                    </Button>
                    
                    <!-- Manual next step button as fallback -->
                    {#if $formWhatsAppState.connectionStatus === 'connected' || $formWhatsAppState.connectionStatus === 'authenticated'}
                        <Button 
                            variant="default"
                            on:click={() => currentStep = 2}
                        >
                            <CheckCircle class="h-4 w-4 mr-2" />
                            Continue to Account Details
                        </Button>
                    {/if}
                </div>
            </FormCard>
        {:else if currentStep === 2}
            <!-- Step 2: Account Details -->
            <FormContainer 
                method="POST" 
                action="?/default" 
                {enhance} 
                novalidate 
                errorMessage={$errorMessage}
            >
                <FormCard title="Account Details" description="Enter account information.">
                    <FormRow columns={1}>
                        <FormField id="description" label="Description" error={$errors.description}>
                            <Textarea
                                id="description"
                                name="description"
                                bind:value={$form.description}
                                placeholder="Describe this WhatsApp account"
                                aria-invalid={$errors.description ? 'true' : undefined}
                                {...$constraints.description}
                            />
                        </FormField>
                    </FormRow>
                    
                    <FormRow columns={1}>
                        <FormField id="client_id" label="Client ID" error={$errors.client_id}>
                            <Input
                                id="client_id"
                                name="client_id"
                                bind:value={$form.client_id}
                                disabled
                                aria-invalid={$errors.client_id ? 'true' : undefined}
                                {...$constraints.client_id}
                            />
                        </FormField>
                    </FormRow>
                    
                    <FormRow columns={1}>
                        <FormField id="phoneNumber" label="Phone Number" error={$errors.phoneNumber}>
                            <Input
                                id="phoneNumber"
                                name="phoneNumber"
                                bind:value={$form.phoneNumber}
                                placeholder="Phone number from WhatsApp"
                                aria-invalid={$errors.phoneNumber ? 'true' : undefined}
                                {...$constraints.phoneNumber}
                            />
                        </FormField>
                    </FormRow>

                    <FormActions>
                        <Button
                            type="button"
                            variant="outline"
                            on:click={() => currentStep = 1}
                            disabled={$submitting}
                        >
                            Back
                        </Button>
                        <Button type="submit" disabled={$submitting} class="min-w-[120px] relative">
                            {#if $submitting}
                                <span class="absolute inset-0 flex items-center justify-center">
                                    <Skeleton class="h-4 w-20" />
                                </span>
                                <span class="opacity-0">Create Account</span>
                            {:else}
                                <Plus class="h-4 w-4 mr-2" />
                                Create Account
                            {/if}
                        </Button>
                    </FormActions>
                </FormCard>
            </FormContainer>
        {:else if currentStep === 3}
            <!-- Step 3: Success Page -->
            <FormCard title="Account Created Successfully" description="Your WhatsApp account has been created successfully.">
                <div class="space-y-6">
                    <div class="flex items-center gap-4">
                        <CheckCircle class="h-6 w-6 text-green-500" />
                        <div>
                            <p class="font-medium">Account Created</p>
                            <p class="text-sm text-muted-foreground">Your WhatsApp account has been created successfully.</p>
                        </div>
                    </div>
                    
                    <div class="bg-muted/40 p-4 rounded-lg border border-muted">
                        <h4 class="text-sm font-medium mb-2">Account Details</h4>
                        <div class="space-y-2">
                            <div>
                                <p class="text-xs text-muted-foreground">Description</p>
                                {#if createdAccount?.description}
                                    <p class="text-sm">{createdAccount.description}</p>
                                {:else}
                                    <Skeleton class="h-4 w-48" />
                                {/if}
                            </div>
                        </div>
                    </div>

                    <FormActions>
                        <Button 
                            variant="outline" 
                            on:click={() => goto('/admin/settings/whatsapp/accounts')}
                        >
                            <ArrowLeft class="h-4 w-4 mr-2" />
                            Back to Accounts
                        </Button>
                    </FormActions>
                </div>
            </FormCard>
        {/if}
    </PageContent>
</PageContainer>
