<script lang="ts">
    import { goto } from "$app/navigation";
    import { toast } from "svelte-sonner";
    import { Button } from "$lib/components/ui/button";
    import { Skeleton } from "$lib/components/ui/skeleton";
    import { ArrowLeft, RefreshCw, CheckCircle, Plus, QrCode, AlertTriangle } from "lucide-svelte";
    import QRCode from "qrcode";
    import PageContainer from "$lib/components/ui_components_sveltekit/layout/PageContainer.svelte";
    import PageHeader from "$lib/components/ui_components_sveltekit/layout/PageHeader.svelte";
    import PageContent from "$lib/components/ui_components_sveltekit/layout/PageContent.svelte";
    import FormCard from "$lib/components/ui_components_sveltekit/form/FormCard.svelte";
    import FormActions from "$lib/components/ui_components_sveltekit/form/FormActions.svelte";
    import AccountForm from "./form.svelte";
    import { whatsAppStore } from "$lib/stores/whatsapp-store";
    import type { ConnectionStatus } from "$lib/stores/whatsapp-store";
    import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "$lib/components/ui/card";
    import type { PageData } from "./$types";
    import { writable } from "svelte/store";
    import { onDestroy, onMount } from "svelte";
  
    // Import the reusable form handler
    import { createFormHandler } from '$lib/components/ui_components_sveltekit/form/utils/formHandler';
    import { createClientMessage, type ClientMessage } from "$lib/types/messages";
    import { socketStore } from "$lib/stores/websocket-store";
  
    export let data: PageData;
    const title = "Create WhatsApp Account";
  
    // Breadcrumbs for this page
    const pageCrumbs = [
      ["Admin", "/admin"],
      "Settings",
      ["Whatsapp", "/admin/settings/whatsapp/accounts"],
      "New Account",
    ];
  
    // Track the current step: 1 = Connect, 2 = Account Details, 3 = Success
    let currentStep = 1;
  
    // Account data after creation
    let createdAccount: { id?: string; description: string } | null = null;
  
    // Use the client ID from the server (generated by Baileys)
    let initialClientId = data.clientId || null;
  
    // Create a store for our form-specific state.
    // We'll use this store directly in the template.
    const formState = writable<{
      clientId: string | null;
      connectionStatus: ConnectionStatus;
      qrCode: string | null;
      pushName: string | null;
      phoneNumber: string | null;
    }>({
      clientId: initialClientId,
      connectionStatus: 'disconnected',
      qrCode: null,
      pushName: null,
      phoneNumber: null,
    });
  
    // Subscribe to the WhatsApp store to update our form state.
    // We update only if the store's clientId matches our form's clientId.
    const unsubscribe = whatsAppStore.subscribe(($store) => {
      console.log('WhatsApp store update:', { 
        storeClientId: $store.clientId, 
        storeQrCode: $store.qrCode ? 'Present' : 'Null',
        storeConnectionStatus: $store.connectionStatus
      });
      
      formState.update(($state) => {
        console.log('Form state before update:', { 
          formClientId: $state.clientId, 
          formQrCode: $state.qrCode ? 'Present' : 'Null',
          formConnectionStatus: $state.connectionStatus
        });
        
        // Update regardless of clientId match for debugging
        const newState = {
          ...$state,
          connectionStatus: $store.connectionStatus,
          qrCode: $store.qrCode,
          pushName: $store.pushName,
          phoneNumber: $store.phoneNumber,
        };
        
        console.log('Form state after update:', { 
          formClientId: newState.clientId, 
          formQrCode: newState.qrCode ? 'Present' : 'Null',
          formConnectionStatus: newState.connectionStatus
        });
        
        return newState;
      });
    });
    onDestroy(unsubscribe);
  
    // For easier reference in reactive blocks and template
    $: $formState;
    
    // Track previous state to detect actual changes
    let previousState = {
      connectionStatus: null,
      clientId: null,
      qrCode: null,
      currentStep: null
    };

    // Debug log for changes (remove or gate in production)
    $: {
      // Only log if this is not the first render and state has actually changed
      const currentState = {
        connectionStatus: $formState.connectionStatus,
        clientId: $formState.clientId,
        qrCode: $formState.qrCode,
        currentStep
      };

      const hasChanged = Object.entries(currentState).some(([key, value]) => {
        return value !== previousState[key];
      });

      if (previousState.connectionStatus !== null && hasChanged) {
        console.log(`WhatsApp form state change:`, {
          ...currentState,
          qrCode: currentState.qrCode ? "present" : "null",
          timestamp: new Date().toISOString(),
          componentId: `whatsapp-form-${Math.random().toString(36).substring(2, 8)}`
        });
      }

      // Update previous state
      previousState = currentState;
    }
    
    // Watch connection status and, if connected/authenticated and on step 1, auto-advance after a delay.
    $: if (
      currentStep === 1 &&
      ($formState.connectionStatus === "connected" || $formState.connectionStatus === "authenticated")
    ) {
      console.log("Connected status detected for form client:", $formState.clientId);
      // Delay to ensure latest data from WhatsApp store
      setTimeout(() => {
        // (Optional) you could also read the latest store data from whatsAppStore.getState()
        const pushName = $formState.pushName || "Unknown";
        const phoneNumber = $formState.phoneNumber || "";
        
        // Update form values directly via the form handler's data object
        $form.description = `WhatsApp Account - ${pushName}`;
        $form.client_id = $formState.clientId;
        $form.name = pushName;
        $form.phoneNumber = phoneNumber;
  
        currentStep = 2;
        toast.success("WhatsApp connected successfully!");
      }, 500);
    }
  
    // Create a form handler with standardized error handling.
    const { form, errors, enhance, submitting, constraints, errorMessage } = createFormHandler(data.form, {
      validateOnInput: true,
      debugMode: true,
      action: "?/createAccount",
      onSuccess: (result) => {
        if (result.data?.account) {
          createdAccount = {
            id: result.data.account.id,
            description: result.data.account.description,
          };
          currentStep = 3;
          toast.success("WhatsApp account created successfully");
        }
      },
      onError: (result) => {
        toast.error(result.form?.message || "Failed to create WhatsApp account");
      },
    });
  
    // Request a new WhatsApp client (which triggers a QR code event).
    // async function requestNewQRCode() {
    //   console.log("Requesting new WhatsApp client");
    //   whatsAppStore.reset();
    //   const toastId = toast.loading("Creating new WhatsApp client...");
  
    //   try {
    //     const response = await fetch("?/requestQRCode", {
    //       method: "POST",
    //       headers: { "Content-Type": "application/json" },
    //     });
    //     const result = await response.json();
  
    //     if (result.success && result.clientId) {
    //       formState.update((state) => ({
    //         ...state,
    //         clientId: result.clientId,
    //         connectionStatus: "disconnected",
    //         qrCode: null,
    //       }));
    //       toast.dismiss(toastId);
    //       toast.success("New WhatsApp client created. Waiting for QR code...");
    //     } else {
    //       toast.dismiss(toastId);
    //       toast.error("Failed to create new WhatsApp client");
    //     }
    //   } catch (error) {
    //     console.error("Error creating new WhatsApp client:", error);
    //     toast.dismiss(toastId);
    //     toast.error("Error creating new WhatsApp client");
    //   }
    // }
  
    // Handle error events from WhatsApp (if any).
    function handleError(event: CustomEvent) {
      console.error("WhatsApp error:", event.detail);
      toast.error(event.detail.message || "An error occurred");
    }
  
    // Manual check: if connection established, update form and advance.
    function checkConnectionAndAdvance() {
      if (
        $formState.connectionStatus === "connected" ||
        $formState.connectionStatus === "authenticated"
      ) {
        const pushName = $formState.pushName || "Unknown";
        const phoneNumber = $formState.phoneNumber || "";
        $form.description = `WhatsApp Account - ${pushName}`;
        $form.client_id = $formState.clientId;
        $form.name = pushName;
        $form.phoneNumber = phoneNumber;
        currentStep = 2;
        toast.success("WhatsApp connected successfully!");
      } else {
        toast.error("WhatsApp is not connected yet. Please scan the QR code first.");
      }
    }
  
    // Generate QR code from data.
    async function generateQRCode(qrCodeData: string) {
      if (!qrCodeData) {
        console.log("No QR code data available");
        return null;
      }
      console.log("Generating QR code from data:", qrCodeData.substring(0, 20) + "...");
      try {
        const url = await QRCode.toDataURL(qrCodeData, {
          errorCorrectionLevel: "H",
          margin: 1,
          width: 256,
          color: {
            dark: "#000000",
            light: "#FFFFFF",
          },
        });
        console.log("QR code generated successfully");
        return url;
      } catch (err) {
        console.error("Error generating QR code:", err);
        throw err;
      }
    }
  
    // Get background color class based on connection status.
    function getStatusBgColor(status: ConnectionStatus): string {
      switch (status) {
        case "awaiting_scan":
          return "bg-amber-50 border border-amber-200";
        case "connecting":
          return "bg-blue-50 border border-blue-200";
        case "connected":
        case "authenticated":
          return "bg-green-50 border border-green-200";
        default:
          return "bg-red-50 border border-red-200";
      }
    }

    // Function to request a new QR code
    function requestNewQRCode() {
        const message: ClientMessage = createClientMessage(
            'whatsapp',
            'user:self',
            {
                action: 'request_qr'
            }
        );

        console.log('Sending message:', message)
        
        socketStore.send(message);
    }

    onMount(() => {
        requestNewQRCode();
    });
  </script>
  
  <PageContainer crumbs={pageCrumbs}>
    <PageHeader title={title} />
    <PageContent>
      {#if currentStep === 1}
        <!-- Step 1: QR Code Display -->
        <FormCard title="Connect WhatsApp" description="Scan the QR code with your WhatsApp app to connect this account.">
          <div class="flex flex-col items-center justify-center space-y-4 p-4">
            <!-- Connection status display -->
            <div class="mb-4 p-3 rounded-md w-full flex items-center gap-2 {getStatusBgColor($formState.connectionStatus)}">
              {#if $formState.connectionStatus === 'awaiting_scan'}
                <QrCode class="h-5 w-5 text-amber-600" />
                <div>
                  <p class="text-sm font-medium">Waiting for QR code scan</p>
                  <p class="text-xs text-muted-foreground">Please scan the QR code with your WhatsApp app</p>
                </div>
              {:else if $formState.connectionStatus === 'connecting'}
                <RefreshCw class="h-5 w-5 text-blue-600 animate-spin" />
                <div>
                  <p class="text-sm font-medium">Connecting</p>
                  <p class="text-xs text-muted-foreground">Establishing connection to WhatsApp...</p>
                </div>
              {:else if $formState.connectionStatus === 'connected'}
                <CheckCircle class="h-5 w-5 text-green-600" />
                <div>
                  <p class="text-sm font-medium">Connected</p>
                  <p class="text-xs text-muted-foreground">WhatsApp connection established</p>
                </div>
              {:else if $formState.connectionStatus === 'authenticated'}
                <CheckCircle class="h-5 w-5 text-green-600" />
                <div>
                  <p class="text-sm font-medium">Authenticated</p>
                  <p class="text-xs text-muted-foreground">Successfully authenticated with WhatsApp</p>
                </div>
              {:else}
                <AlertTriangle class="h-5 w-5 text-red-600" />
                <div>
                  <p class="text-sm font-medium">Disconnected</p>
                  <p class="text-xs text-muted-foreground">Not connected to WhatsApp</p>
                </div>
              {/if}
            </div>
  
            {#if $formState.qrCode}
              <!-- Display the generated QR code -->
              <div class="w-64 h-64 border border-border rounded-md overflow-hidden flex items-center justify-center bg-white">
                {#await generateQRCode($formState.qrCode)}
                  <Skeleton class="h-64 w-64" />
                {:then qrCodeUrl}
                  <img src={qrCodeUrl} alt="WhatsApp QR Code" class="w-full h-full object-contain" />
                {:catch error}
                  <div class="text-center text-destructive">
                    <AlertTriangle class="h-12 w-12 mx-auto mb-2" />
                    <p class="text-sm">Failed to generate QR code</p>
                  </div>
                {/await}
              </div>
              <p class="text-sm text-center text-muted-foreground">Scan this QR code with your WhatsApp app to connect</p>
            {:else if $formState.connectionStatus === 'connecting'}
              <div class="w-64 h-64 flex items-center justify-center">
                <Skeleton class="h-64 w-64" />
              </div>
              <Skeleton class="h-4 w-48" />
            {:else}
              <div class="w-64 h-64 border-2 border-dashed border-muted-foreground rounded-md flex items-center justify-center">
                <div class="text-center">
                  <QrCode class="h-12 w-12 mx-auto mb-2 text-muted-foreground" />
                  <p class="text-sm text-muted-foreground">QR code not available</p>
                </div>
              </div>
              <p class="text-sm text-center text-muted-foreground">Click the button below to request a QR code</p>
            {/if}
          </div>
  
          <div class="mt-4 flex flex-col gap-2">
            <!-- Uncomment below button to allow manual QR code request -->
            <!--
            <Button variant="outline" size="sm" on:click={requestNewQRCode}>
              <RefreshCw class="h-4 w-4 mr-2" />
              Request New QR Code
            </Button>
            -->
            {#if $formState.connectionStatus === 'connected' || $formState.connectionStatus === 'authenticated'}
              <Button variant="default" on:click={() => currentStep = 2}>
                <CheckCircle class="h-4 w-4 mr-2" />
                Continue to Account Details
              </Button>
            {/if}
          </div>
        </FormCard>
      {:else if currentStep === 2}
        <!-- Step 2: Account Details -->
        <AccountForm 
          form={$form}
          errors={$errors}
          enhance={enhance}
          submitting={$submitting}
          constraints={$constraints}
          errorMessage={$errorMessage}
          on:goBack={() => currentStep = 1}
        />
      {:else if currentStep === 3}
        <!-- Step 3: Success -->
        <FormCard title="Account Created Successfully" description="Your WhatsApp account has been created successfully.">
          <div class="space-y-6">
            <div class="bg-muted/40 p-4 rounded-lg border border-muted">
              <h4 class="text-sm font-medium mb-2">Account Details</h4>
              <div class="space-y-2">
                <CheckCircle class="h-6 w-6 text-green-500" />
                <div>
                  <p class="text-xs text-muted-foreground">Description</p>
                  {#if createdAccount?.description}
                    <p class="text-sm">{createdAccount.description}</p>
                  {:else}
                    <Skeleton class="h-4 w-48" />
                  {/if}
                </div>
              </div>
            </div>
            <FormActions>
              <Button variant="outline" on:click={() => goto('/admin/settings/whatsapp/accounts')}>
                <ArrowLeft class="h-4 w-4 mr-2" />
                Back to Accounts
              </Button>
            </FormActions>
          </div>
        </FormCard>
      {/if}
    </PageContent>
  </PageContainer>
  