CREATE TABLE logs_raw
(
    `c1` DateTime,
    `c2` String,
    `c3` String,
    `c4` String,
    `c5` String,
    `c6` String,
    `c7` String,
    `c8` String,
    `c9` String,
    `c10` String,
    `c11` String,
    `c12` String,
    `c13` String,
    `c14` String,
    `c15` String,
    `c16` String,
    `c17` String,
    `c18` String,
    `c19` String,
    `c20` String,
    `c21` String,
    `c22` String,
    `c23` String,
    `c24` String,
    `c25` String,
    `c26` String,
    `c27` String,
    `c28` String,
    `c29` String,
    `c30` String,
    `c31` String,
    `c32` String,
    `c33` String,
    `c34` String,
    `c35` String,
    `c36` String,
    `c37` String,
    `c38` String,
    `c39` String,
    `c40` String,
    `c41` String,
    `c42` String,
    `c43` String,
    `c44` String,
    `c45` String,
    `c46` String,
    `c47` String,
    `c48` String,
    `c49` String,
    `c50` String,
    `c51` String,
    `c52` String,
    `c53` String,
    `c54` String,
    `c55` String,
    `c56` String,
    `c57` String,
    `c58` String,
    `c59` String,
    `c60` String
)
ENGINE = MergeTree
ORDER BY (toDate(c1), c2, c4)
SETTINGS index_granularity = 8192
